"""Manage API keys and .env file generation."""

from __future__ import annotations

import os
import stat
from pathlib import Path
from typing import Any

from consortium.cli.core.config_manager import get_config_dir


# API key definitions: name, env var, provider, required level
API_KEYS = [
    {
        "name": "Anthropic",
        "env_var": "ANTHROPIC_API_KEY",
        "provider": "anthropic",
        "level": "required",
        "description": "Claude models (Opus, Sonnet) — primary research models",
        "prefix": "sk-ant-",
    },
    {
        "name": "OpenAI",
        "env_var": "OPENAI_API_KEY",
        "provider": "openai",
        "level": "required",
        "description": "GPT-5 models — used in counsel mode debates",
        "prefix": "sk-",
    },
    {
        "name": "Google AI",
        "env_var": "GOOGLE_API_KEY",
        "provider": "google",
        "level": "recommended",
        "description": "Gemini models — recommended for counsel mode (3-model debate)",
        "prefix": "",
    },
    {
        "name": "DeepSeek",
        "env_var": "DEEPSEEK_API_KEY",
        "provider": "deepseek",
        "level": "optional",
        "description": "DeepSeek models — cost-effective alternative",
        "prefix": "",
    },
    {
        "name": "xAI",
        "env_var": "XAI_API_KEY",
        "provider": "xai",
        "level": "optional",
        "description": "Grok models",
        "prefix": "",
    },
    {
        "name": "SerpAPI",
        "env_var": "SERPER_API_KEY",
        "provider": "serper",
        "level": "optional",
        "description": "Web search for literature discovery",
        "prefix": "",
    },
]

NOTIFICATION_KEYS = [
    {
        "name": "Telegram Bot Token",
        "env_var": "TELEGRAM_BOT_TOKEN",
        "description": "Telegram bot for pipeline notifications",
    },
    {
        "name": "Telegram Chat ID",
        "env_var": "TELEGRAM_CHAT_ID",
        "description": "Your Telegram chat/group ID for notifications",
    },
    {
        "name": "Slack Webhook",
        "env_var": "SLACK_WEBHOOK_URL",
        "description": "Slack incoming webhook for notifications",
    },
]


def get_env_file_path(config_dir_override: str | None = None) -> Path:
    """Return the path to the .env file."""
    return get_config_dir(config_dir_override) / ".env"


def load_env_vars(config_dir_override: str | None = None) -> dict[str, str]:
    """Load existing env vars from the .env file."""
    env_path = get_env_file_path(config_dir_override)
    if not env_path.exists():
        return {}

    env_vars: dict[str, str] = {}
    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and value:
                    env_vars[key] = value
    return env_vars


def save_env_file(
    env_vars: dict[str, str],
    config_dir_override: str | None = None,
) -> Path:
    """Write env vars to ~/.msc/.env with restricted permissions."""
    env_path = get_env_file_path(config_dir_override)

    lines = [
        "# PoggioAI/MSc API Keys — generated by `msc setup`",
        "# DO NOT commit this file to version control.",
        "",
    ]

    # Group by category
    api_vars = {k: v for k, v in env_vars.items() if k.endswith("_API_KEY") or k.endswith("_KEY")}
    notif_vars = {k: v for k, v in env_vars.items() if k.startswith(("TELEGRAM_", "SLACK_"))}
    other_vars = {k: v for k, v in env_vars.items() if k not in api_vars and k not in notif_vars}

    if api_vars:
        lines.append("# LLM API Keys")
        for k, v in sorted(api_vars.items()):
            lines.append(f'{k}="{v}"')
        lines.append("")

    if notif_vars:
        lines.append("# Notification Credentials")
        for k, v in sorted(notif_vars.items()):
            lines.append(f'{k}="{v}"')
        lines.append("")

    if other_vars:
        lines.append("# Other")
        for k, v in sorted(other_vars.items()):
            lines.append(f'{k}="{v}"')
        lines.append("")

    with open(env_path, "w") as f:
        f.write("\n".join(lines))

    # Restrict permissions: owner read/write only
    os.chmod(env_path, stat.S_IRUSR | stat.S_IWUSR)

    return env_path


def inject_env(config_dir_override: str | None = None) -> None:
    """Load .env vars into the current process environment.

    Called before spawning consortium subprocess so it inherits the keys.
    """
    env_vars = load_env_vars(config_dir_override)
    for key, value in env_vars.items():
        if key not in os.environ:
            os.environ[key] = value


def check_required_keys(config_dir_override: str | None = None) -> list[dict[str, Any]]:
    """Check which required/recommended API keys are configured.

    Returns a list of dicts with 'name', 'env_var', 'level', 'configured' fields.
    """
    env_vars = load_env_vars(config_dir_override)
    results = []
    for key_info in API_KEYS:
        configured = bool(
            env_vars.get(key_info["env_var"]) or os.environ.get(key_info["env_var"])
        )
        results.append({**key_info, "configured": configured})
    return results


def has_any_llm_key(config_dir_override: str | None = None) -> bool:
    """Check if at least one LLM API key is configured."""
    results = check_required_keys(config_dir_override)
    return any(
        r["configured"]
        for r in results
        if r["level"] in ("required", "recommended") and r["provider"] != "serper"
    )
