"""Manage API keys and .env file generation."""

from __future__ import annotations

import os
import stat
from pathlib import Path
from typing import Any

from consortium.cli.core.config_manager import get_config_dir

_TRUEISH = {"1", "true", "yes", "on"}
_FALSEISH = {"0", "false", "no", "off"}


# API key definitions: name, env var, provider, required level
API_KEYS = [
    {
        "name": "OpenRouter",
        "env_var": "OPENROUTER_API_KEY",
        "provider": "openrouter",
        "level": "required",
        "description": "All models via OpenRouter (single key for Claude, GPT, Gemini, etc.)",
        "prefix": "sk-or-",
    },
    {
        "name": "Anthropic",
        "env_var": "ANTHROPIC_API_KEY",
        "provider": "anthropic",
        "level": "optional",
        "description": "Claude models directly (alternative to OpenRouter)",
        "prefix": "sk-ant-",
    },
    {
        "name": "OpenAI",
        "env_var": "OPENAI_API_KEY",
        "provider": "openai",
        "level": "optional",
        "description": "GPT models directly (alternative to OpenRouter)",
        "prefix": "sk-",
    },
    {
        "name": "Google AI",
        "env_var": "GOOGLE_API_KEY",
        "provider": "google",
        "level": "optional",
        "description": "Gemini models directly (alternative to OpenRouter)",
        "prefix": "",
    },
    {
        "name": "DeepSeek",
        "env_var": "DEEPSEEK_API_KEY",
        "provider": "deepseek",
        "level": "optional",
        "description": "DeepSeek models — cost-effective alternative",
        "prefix": "",
    },
    {
        "name": "xAI",
        "env_var": "XAI_API_KEY",
        "provider": "xai",
        "level": "optional",
        "description": "Grok models",
        "prefix": "",
    },
    {
        "name": "SerpAPI",
        "env_var": "SERPER_API_KEY",
        "provider": "serper",
        "level": "optional",
        "description": "Web search for literature discovery",
        "prefix": "",
    },
]

NOTIFICATION_KEYS = [
    {
        "name": "Telegram Bot Token",
        "env_var": "TELEGRAM_BOT_TOKEN",
        "description": "Telegram bot for pipeline notifications",
    },
    {
        "name": "Telegram Chat ID",
        "env_var": "TELEGRAM_CHAT_ID",
        "description": "Your Telegram chat/group ID for notifications",
    },
    {
        "name": "Slack Webhook",
        "env_var": "SLACK_WEBHOOK_URL",
        "description": "Slack incoming webhook for notifications",
    },
]


def _load_env_file(path: Path) -> dict[str, str]:
    """Load KEY=VALUE pairs from an env file."""
    if not path.exists():
        return {}

    env_vars: dict[str, str] = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and value:
                    env_vars[key] = value
    return env_vars


def get_env_file_path(config_dir_override: str | None = None) -> Path:
    """Return the path to the .env file."""
    return get_config_dir(config_dir_override) / ".env"


def load_env_vars(config_dir_override: str | None = None) -> dict[str, str]:
    """Load existing env vars from the .env file."""
    return _load_env_file(get_env_file_path(config_dir_override))


def load_repo_env_vars(repo_root: str | Path | None = None) -> dict[str, str]:
    """Load env vars from the repo-root .env file when present."""
    if repo_root is None:
        return {}
    return _load_env_file(Path(repo_root) / ".env")


def save_env_file(
    env_vars: dict[str, str],
    config_dir_override: str | None = None,
) -> Path:
    """Write env vars to ~/.msc/.env with restricted permissions."""
    env_path = get_env_file_path(config_dir_override)

    lines = [
        "# PoggioAI/MSc API Keys — generated by `msc setup`",
        "# DO NOT commit this file to version control.",
        "",
    ]

    # Group by category
    api_vars = {k: v for k, v in env_vars.items() if k.endswith("_API_KEY") or k.endswith("_KEY")}
    notif_vars = {k: v for k, v in env_vars.items() if k.startswith(("TELEGRAM_", "SLACK_"))}
    other_vars = {k: v for k, v in env_vars.items() if k not in api_vars and k not in notif_vars}

    if api_vars:
        lines.append("# LLM API Keys")
        for k, v in sorted(api_vars.items()):
            lines.append(f'{k}="{v}"')
        lines.append("")

    if notif_vars:
        lines.append("# Notification Credentials")
        for k, v in sorted(notif_vars.items()):
            lines.append(f'{k}="{v}"')
        lines.append("")

    if other_vars:
        lines.append("# Other")
        for k, v in sorted(other_vars.items()):
            lines.append(f'{k}="{v}"')
        lines.append("")

    with open(env_path, "w") as f:
        f.write("\n".join(lines))

    # Restrict permissions: owner read/write only
    os.chmod(env_path, stat.S_IRUSR | stat.S_IWUSR)

    return env_path


def _should_use_repo_env(
    repo_root: str | Path | None,
    allow_repo_env: bool | None,
) -> bool:
    """Return whether repo-root .env should participate in env resolution."""
    if repo_root is None:
        return False
    if allow_repo_env is not None:
        return allow_repo_env

    env_override = os.getenv("CONSORTIUM_USE_REPO_ENV", "").strip().lower()
    if env_override in _TRUEISH:
        return True
    if env_override in _FALSEISH:
        return False

    repo_path = Path(repo_root).resolve()
    try:
        cwd = Path.cwd().resolve()
    except OSError:
        return False
    return cwd == repo_path or repo_path in cwd.parents


def _merge_runtime_env(
    *,
    config_dir_override: str | None = None,
    repo_root: str | Path | None = None,
    base_env: dict[str, str] | None = None,
    allow_repo_env: bool | None = None,
) -> tuple[dict[str, str], dict[str, str]]:
    env = dict(base_env or os.environ)
    sources = {key: "shell" for key, value in env.items() if value}
    protected = set(sources)

    include_repo_env = _should_use_repo_env(repo_root, allow_repo_env)
    if include_repo_env:
        for key, value in load_repo_env_vars(repo_root).items():
            if not env.get(key):
                env[key] = value
                sources[key] = "repo-env"

    for key, value in load_env_vars(config_dir_override).items():
        if key in protected:
            continue
        env[key] = value
        sources[key] = "config-dir"

    return env, sources


def build_runtime_env(
    *,
    config_dir_override: str | None = None,
    repo_root: str | Path | None = None,
    base_env: dict[str, str] | None = None,
    allow_repo_env: bool | None = None,
) -> dict[str, str]:
    """Merge shell, config-dir, and repo-local env layers.

    Precedence:
    1. Existing process environment
    2. ~/.msc/.env
    3. repo-root .env (only when explicitly allowed or running from repo root)
    """
    env, _ = _merge_runtime_env(
        config_dir_override=config_dir_override,
        repo_root=repo_root,
        base_env=base_env,
        allow_repo_env=allow_repo_env,
    )
    return env


def inject_runtime_env(
    *,
    config_dir_override: str | None = None,
    repo_root: str | Path | None = None,
    allow_repo_env: bool | None = None,
) -> None:
    """Load repo-local and ~/.msc env layers into the current process."""
    os.environ.update(
        build_runtime_env(
            config_dir_override=config_dir_override,
            repo_root=repo_root,
            base_env=dict(os.environ),
            allow_repo_env=allow_repo_env,
        )
    )


def inject_env(config_dir_override: str | None = None) -> None:
    """Load ~/.msc/.env vars into the current process environment."""
    env_vars = load_env_vars(config_dir_override)
    for key, value in env_vars.items():
        if key not in os.environ:
            os.environ[key] = value


def check_required_keys(
    config_dir_override: str | None = None,
    *,
    repo_root: str | Path | None = None,
    allow_repo_env: bool | None = None,
) -> list[dict[str, Any]]:
    """Check which required/recommended API keys are configured.

    Returns a list of dicts with 'name', 'env_var', 'level', 'configured' fields.
    """
    env_vars, sources = _merge_runtime_env(
        config_dir_override=config_dir_override,
        repo_root=repo_root,
        allow_repo_env=allow_repo_env,
    )
    results = []
    for key_info in API_KEYS:
        configured = bool(env_vars.get(key_info["env_var"]))
        results.append({
            **key_info,
            "configured": configured,
            "source": sources.get(key_info["env_var"]),
        })
    return results


def has_required_llm_key(
    config_dir_override: str | None = None,
    *,
    repo_root: str | Path | None = None,
    allow_repo_env: bool | None = None,
) -> bool:
    """Return True when the required OpenRouter key is configured."""
    env_vars = build_runtime_env(
        config_dir_override=config_dir_override,
        repo_root=repo_root,
        allow_repo_env=allow_repo_env,
    )
    return bool(env_vars.get("OPENROUTER_API_KEY"))


def get_runtime_env_sources(
    config_dir_override: str | None = None,
    *,
    repo_root: str | Path | None = None,
    allow_repo_env: bool | None = None,
    base_env: dict[str, str] | None = None,
) -> dict[str, str]:
    """Return the winning source for each resolved environment variable."""
    _, sources = _merge_runtime_env(
        config_dir_override=config_dir_override,
        repo_root=repo_root,
        allow_repo_env=allow_repo_env,
        base_env=base_env,
    )
    return sources


def has_any_llm_key(config_dir_override: str | None = None) -> bool:
    """Check if at least one LLM API key is configured.

    Returns True if OpenRouter key is set (sufficient for all models) or
    if any direct provider key (Anthropic, OpenAI, Google) is set.
    """
    results = check_required_keys(config_dir_override)
    return any(
        r["configured"]
        for r in results
        if r["provider"] not in ("serper",)
        and r["env_var"].endswith("_API_KEY")
    )
