"""Generate .llm_config.yaml from a price tier definition."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import yaml

from consortium.cli.core.model_policy import (
    build_default_persona_specs,
    normalize_model_settings,
    persona_spec_to_runtime_spec,
)
from consortium.cli.core.presets import Preset


# Pricing table — constant across all tiers (model cost data, not a config choice)
_PRICING: dict[str, dict[str, float]] = {
    "claude-opus-4-6": {"input_per_1k": 0.005, "output_per_1k": 0.025},
    "claude-sonnet-4-6": {"input_per_1k": 0.003, "output_per_1k": 0.015},
    "claude-sonnet-4-5": {"input_per_1k": 0.003, "output_per_1k": 0.015},
    "gpt-5": {"input_per_1k": 0.002, "output_per_1k": 0.012},
    "gpt-5.2": {"input_per_1k": 0.00175, "output_per_1k": 0.014},
    "gpt-5.4": {"input_per_1k": 0.0025, "output_per_1k": 0.015},
    "gpt-5.3-codex": {"input_per_1k": 0.002, "output_per_1k": 0.01},
    "gpt-5-mini": {"input_per_1k": 0.0004, "output_per_1k": 0.0016},
    "gemini-3-pro-preview": {"input_per_1k": 0.00125, "output_per_1k": 0.01},
    "deepseek-chat": {"input_per_1k": 0.00014, "output_per_1k": 0.00028},
}

_HEADER = (
    "# =============================================================================\n"
    "# PoggioAI/MSc LLM Configuration\n"
    "# =============================================================================\n"
    "# Auto-generated by msc from tier '{tier_name}'. Edits will be overwritten\n"
    "# on the next run unless you set custom_llm_config: true in ~/.msc/config.yaml.\n"
)


def tier_to_llm_config(tier: Preset) -> dict[str, Any]:
    """Build a complete .llm_config.yaml dict from a tier definition."""
    cfg: dict[str, Any] = {}

    # --- Main model ---
    main = normalize_model_settings(
        tier.model,
        {
            "model": tier.model,
            "reasoning_effort": tier.reasoning_effort,
            **({"budget_tokens": tier.budget_tokens} if tier.budget_tokens else {}),
        },
    )
    cfg["main_agents"] = main
    cfg["summary_model"] = {"model": tier.model}

    # --- Experiment tool models ---
    if tier.experiment_tool_models:
        cfg["run_experiment_tool"] = dict(tier.experiment_tool_models)
    else:
        cfg["run_experiment_tool"] = {
            "code_model": tier.model,
            "feedback_model": tier.model,
            "vlm_model": tier.model,
            "report_model": tier.model,
        }

    # --- Budget ---
    cfg["budget"] = {
        "usd_limit": tier.budget_usd,
        "hard_stop": True,
        "fail_closed": True,
        "pricing": _PRICING,
    }

    # --- Counsel ---
    counsel: dict[str, Any] = {"enabled": tier.enable_counsel}
    if tier.enable_counsel and tier.counsel_model_specs:
        counsel["max_debate_rounds"] = tier.counsel_debate_rounds
        counsel["synthesis_model"] = tier.counsel_synthesis_model or tier.model
        counsel["models"] = [
            normalize_model_settings(str(spec["model"]), dict(spec))
            for spec in tier.counsel_model_specs
        ]
    else:
        counsel["max_debate_rounds"] = 0
        counsel["synthesis_model"] = tier.model
        counsel["models"] = []
    cfg["counsel"] = counsel

    # --- Persona council ---
    cfg["persona_council"] = {
        "max_debate_rounds": tier.counsel_debate_rounds if tier.enable_counsel else 3,
        "synthesis_model": tier.counsel_synthesis_model or tier.model,
    }
    persona_specs = (
        [persona_spec_to_runtime_spec(dict(spec)) for spec in tier.persona_council_specs]
        if tier.persona_council_specs
        else build_default_persona_specs(
            model=tier.model,
            reasoning_effort=tier.reasoning_effort,
            budget_tokens=tier.budget_tokens,
        )
    )
    cfg["persona_council"]["personas"] = persona_specs
    if tier.persona_post_vote_retries is not None:
        cfg["persona_council"]["max_post_vote_retries"] = tier.persona_post_vote_retries

    # --- Duality check ---
    cfg["duality_check"] = {"model": tier.model}

    # --- Per-agent model tiers ---
    pa: dict[str, Any] = {"enabled": tier.per_agent_models_enabled}
    if tier.per_agent_models_enabled and tier.per_agent_tiers:
        pa["tiers"] = {
            name: normalize_model_settings(str(config["model"]), dict(config))
            for name, config in tier.per_agent_tiers
        }
        if tier.agent_tier_assignments:
            pa["agent_tiers"] = {agent: t for agent, t in tier.agent_tier_assignments}
    cfg["per_agent_models"] = pa

    return cfg


def apply_overrides(
    cfg: dict[str, Any],
    *,
    model: Optional[str] = None,
    budget_usd: Optional[int] = None,
    counsel: Optional[bool] = None,
) -> dict[str, Any]:
    """Apply CLI overrides on top of a tier-generated config."""
    if model:
        cfg["main_agents"]["model"] = model
        cfg["duality_check"]["model"] = model
        # If counsel is off, also update synthesis model
        if not cfg["counsel"]["enabled"]:
            cfg["counsel"]["synthesis_model"] = model
            cfg["persona_council"]["synthesis_model"] = model
    if budget_usd is not None:
        cfg["budget"]["usd_limit"] = budget_usd
    if counsel is True:
        cfg["counsel"]["enabled"] = True
    elif counsel is False:
        cfg["counsel"]["enabled"] = False
        cfg["counsel"]["models"] = []
        cfg["counsel"]["max_debate_rounds"] = 0
    return cfg


def write_llm_config(
    tier: Preset,
    path: str = ".llm_config.yaml",
    *,
    overrides: Optional[dict[str, Any]] = None,
) -> Path:
    """Generate and write .llm_config.yaml for the given tier.

    Returns the path written to.
    """
    cfg = tier_to_llm_config(tier)
    if overrides:
        cfg = apply_overrides(
            cfg,
            model=overrides.get("model"),
            budget_usd=overrides.get("budget_usd"),
            counsel=overrides.get("counsel"),
        )

    header = _HEADER.format(tier_name=tier.name)
    body = yaml.dump(cfg, default_flow_style=False, sort_keys=False)

    out = Path(path)
    out.write_text(header + "\n" + body)
    return out
