"""msc run — execute a research pipeline."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.table import Table

from consortium.cli.core.config_manager import load_config
from consortium.cli.core.env_manager import has_any_llm_key, inject_env
from consortium.cli.core.flag_translator import build_argv
from consortium.cli.core.llm_config_generator import write_llm_config
from consortium.cli.core.presets import PRESETS, TIERS, TIER_ORDER, resolve_tier_name

console = Console()


@click.command()
@click.argument("task", required=False)
@click.option(
    "--tier", "-t",
    type=click.Choice(list(TIER_ORDER)),
    default=None,
    help="Price tier: budget ($20-50), light ($50-100), medium ($100-300), pro ($300-500), max ($500+).",
)
@click.option(
    "--preset", "-p",
    type=click.Choice(list(PRESETS.keys())),
    default=None,
    hidden=True,
    help="Deprecated — use --tier instead.",
)
@click.option("--task-file", "-f", type=click.Path(exists=True), help="Read task from a file.")
@click.option("--model", "-m", type=str, default=None, help="Override the LLM model.")
@click.option("--budget", "-b", type=int, default=None, help="Override the budget in USD.")
@click.option("--output-format", "-o", type=click.Choice(["markdown", "latex"]), default=None)
@click.option("--mode", type=click.Choice(["local", "tinker", "hpc"]), default=None)
@click.option("--dry-run", is_flag=True, help="Validate setup without running (no cost).")
@click.option("--counsel/--no-counsel", default=None, help="Enable/disable multi-model counsel.")
@click.option("--math/--no-math", default=None, help="Enable/disable math agents.")
@click.option("--tree-search/--no-tree-search", default=None, help="Enable/disable tree search.")
@click.option("--max-run-seconds", type=int, default=None, help="Hard timeout in seconds.")
@click.option("--stream/--no-stream", default=True, help="Enable/disable streaming display.")
@click.pass_context
def run(
    ctx: click.Context,
    task: str | None,
    tier: str | None,
    preset: str | None,
    task_file: str | None,
    model: str | None,
    budget: int | None,
    output_format: str | None,
    mode: str | None,
    dry_run: bool,
    counsel: bool | None,
    math: bool | None,
    tree_search: bool | None,
    max_run_seconds: int | None,
    stream: bool,
) -> None:
    """Run a research pipeline on a question or topic.

    \b
    Examples:
      msc run "How do transformers handle long-range dependencies?"
      msc run --tier pro "Prove the Goldbach conjecture for small primes"
      msc run --task-file my_task.txt --tier max
      msc run "Quick survey of GAN architectures" --tier budget --dry-run
    """
    # Resolve task
    if task_file and not task:
        with open(task_file, "r") as f:
            task = f.read().strip()
    if not task:
        console.print("[bold white on red] Error [/] Provide a research task as an argument or via --task-file.")
        raise SystemExit(1)

    config_dir = ctx.obj.get("config_dir")
    quiet = ctx.obj.get("quiet", False)

    # Check for API keys
    if not has_any_llm_key(config_dir):
        console.print(
            "[bold white on red] Error [/] No API keys configured. Run [bold white]msc setup[/] first."
        )
        raise SystemExit(1)

    # ── Resolve tier ────────────────────────────────────────────────
    # Priority: --tier > --preset (backward compat) > config.yaml > default
    tier_name: str | None = tier
    if tier_name is None and preset is not None:
        tier_name = resolve_tier_name(preset)
    if tier_name is None:
        user_cfg = load_config(config_dir)
        tier_name = user_cfg.get("tier") or user_cfg.get("preset")
    if tier_name is None:
        tier_name = "medium"
    tier_name = resolve_tier_name(tier_name)
    selected_tier = TIERS[tier_name]

    # ── Generate .llm_config.yaml from tier ─────────────────────────
    user_cfg = load_config(config_dir)
    if not user_cfg.get("custom_llm_config", False):
        # Guard: don't overwrite a hand-edited config without warning
        _cfg_path = Path(".llm_config.yaml")
        _should_write = True
        if _cfg_path.exists():
            try:
                _head = _cfg_path.read_text()[:300]
                if "Auto-generated by msc" not in _head:
                    console.print(
                        "[dim]Skipping .llm_config.yaml generation — file appears hand-edited.[/]\n"
                        "[dim]Set custom_llm_config: true in ~/.msc/config.yaml to silence this,[/]\n"
                        "[dim]or delete .llm_config.yaml to let msc regenerate it.[/]"
                    )
                    _should_write = False
            except OSError:
                pass
        if _should_write:
            llm_overrides: dict = {}
            if model:
                llm_overrides["model"] = model
            if budget is not None:
                llm_overrides["budget_usd"] = budget
            if counsel is not None:
                llm_overrides["counsel"] = counsel
            write_llm_config(selected_tier, ".llm_config.yaml", overrides=llm_overrides or None)

    # Build overrides from CLI flags
    overrides: dict[str, object] = {"dry_run": dry_run}
    if model:
        overrides["model"] = model
    if budget is not None:
        overrides["budget_usd"] = budget
    if output_format:
        overrides["output_format"] = output_format
    if mode:
        overrides["mode"] = mode
    if max_run_seconds:
        overrides["max_run_seconds"] = max_run_seconds
    if counsel is True:
        overrides["enable_counsel"] = True
        overrides["no_counsel"] = False
    elif counsel is False:
        overrides["enable_counsel"] = False
        overrides["no_counsel"] = True
    if math is True:
        overrides["enable_math_agents"] = True
    elif math is False:
        overrides["enable_math_agents"] = False
    if tree_search is True:
        overrides["enable_tree_search"] = True
    elif tree_search is False:
        overrides["enable_tree_search"] = False

    # Build argv
    argv = build_argv(task, tier_name, **overrides)

    # Show run summary
    if not quiet:
        effective_model = model or selected_tier.model
        effective_budget = budget or selected_tier.budget_usd
        counsel_status = "off"
        if counsel is True or (counsel is None and selected_tier.enable_counsel):
            specs = selected_tier.counsel_model_specs
            counsel_status = f"on ({len(specs)} models)" if specs else "on"
        elif counsel is False:
            counsel_status = "off"

        table = Table(
            title="[bold white]Run Configuration[/]",
            show_header=False,
            padding=(0, 2),
            border_style="bright_black",
        )
        table.add_column("Key", style="bold blue")
        table.add_column("Value", style="white")
        table.add_row("Task", task[:80] + ("..." if len(task) > 80 else ""))
        table.add_row("Tier", f"{selected_tier.tier_label} ({selected_tier.budget_range})")
        table.add_row("Model", effective_model)
        table.add_row("Budget", f"${effective_budget}")
        table.add_row("Output", output_format or selected_tier.output_format)
        table.add_row("Counsel", counsel_status)
        table.add_row("Dry run", "yes" if dry_run else "no")
        console.print(table)
        console.print()

    # Inject API keys into environment
    inject_env(config_dir)

    # Run consortium
    if not quiet:
        console.print("[bold blue]\u25b6 Starting pipeline...[/]")
        console.print(f"[dim]$ {' '.join(argv)}[/dim]\n")

    env = dict(**os.environ)

    # Use streaming display if available and requested
    use_streaming = stream and not dry_run and not quiet and sys.stdout.isatty()

    if use_streaming:
        try:
            from consortium.cli.display import StreamingDisplay
            effective_budget = budget or selected_tier.budget_usd
            display = StreamingDisplay(budget=effective_budget)
            rc = display.run(argv, env)
            raise SystemExit(rc)
        except ImportError:
            pass  # Fall back to simple run

    try:
        proc = subprocess.run(argv, env=env)
        raise SystemExit(proc.returncode)
    except FileNotFoundError:
        console.print(
            "[bold white on red] Error [/] 'consortium' command not found. "
            "Install it with: [bold white]pip install -e .[/]"
        )
        raise SystemExit(1)
